# Generated by Django 5.2.1 on 2025-05-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_profile_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_blog_status_e6780b_idx',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
